# fly.toml file generated for cheapo on 2023-02-04T13:17:53-08:00

app = "cheapo"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

# [build]
  # This is what tells fly.io to use a Python config instead of generic Docker.
  # But don't use it, because it sucks. If you SSH in, then Python isn't even
  # available to run migrations. Boo.
  # builder = "paketobuildpacks/builder:full"

[env]
  FLASK_SQLALCHEMY_DATABASE_URI = "sqlite:////var/lib/data/app.db"
  FLASK_MAINTENANCE_MODE = 0
  PORT = "8080"

[experimental]
  auto_rollback = true

[mounts]
  destination = "/var/lib/data"
  source = "data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/_health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
