# This file determines how the web site is configured on Render.com.
# For fly.io, see Procfile and fly.toml.
services:
  - type: web
    name: cheapo # probably updated this
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    healthCheckPath: /_health
    disk:
      name: db-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: FLASK_SQLALCHEMY_DATABASE_URI
        value: "sqlite:////data/app.db"
      - key: PYTHON_VERSION
        value: 3.9.13
      # Be sure to set FLASK_SECRET_KEY in Render!
