services:
  - type: web
    name: cheapo # probably updated this
    env: python
    plan: starter
    # buildCommand: yarn install && yarn build
    startCommand: rsync -a public/ /data/public/ && gunicorn server:app
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: db-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: "sqlite://data/app.db"
      - key: PYTHON_VERSION
        value: 3.9.13
