services:
  - type: web
    name: cheapo
    env: python
    plan: starter
    # buildCommand: yarn install && yarn build
    startCommand: rsync -a public/ /data/public/ && yarn start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: "sqlite://data/app.db"
